### PR TITLE
app page and style.css

### PR DESCRIPTION
**Pull request by hnaht310**
add app.html, make changes to style.css, and add background image

### CODE REVIEW

**Review by HenRMJ — APPROVED** [review]
LGTM!

**Review by LVnereus1 — APPROVED** [review]

**Review by niajohnson26 — CHANGES_REQUESTED** [review]
Waiting for label change.

**Review by HenRMJ — APPROVED** [review]
Cool Looks good

**Review by LVnereus1 — APPROVED** [review]
Updated labels looks good.

**Review by niajohnson26 — APPROVED** [review]

**Pull request merged**
